$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1419008310313.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"NewVariable"],
  "page":{
    "packageId":"f32e910147274cdaa20f2865116c6032",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dedcfccc1b59419d8105fbb8b7f333f9",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":190},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b362a220990d4e8085493223e22c81a5",
              "label":"Home",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7650ad05a006498e8d890e609aa66baa",
                  "label":"",
                  "parentDynamicPanel":"dedcfccc1b59419d8105fbb8b7f333f9",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":790,
                      "height":304}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7e9fc38d624c4b6484f19b0f55cb8a11",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dedcfccc1b59419d8105fbb8b7f333f9",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":790,
                          "height":304}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"cbf10ef8faf443cf8cdc4b7aad0f6d83",
              "label":"Search-typed",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f22def401026474aa3e7c21cccf8f7fe",
                  "label":"",
                  "parentDynamicPanel":"dedcfccc1b59419d8105fbb8b7f333f9",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":-2,
                      "y":-1},
                    "size":{
                      "width":790,
                      "height":304}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"24f4f616dac74aff868fc0d4ae3d31d2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"dedcfccc1b59419d8105fbb8b7f333f9",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":-2,
                          "y":-1},
                        "size":{
                          "width":790,
                          "height":304}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u3.png"}},
{
                  "id":"6950c9515d0b4c6e87a9805765d63432",
                  "label":"",
                  "parentDynamicPanel":"dedcfccc1b59419d8105fbb8b7f333f9",
                  "panelIndex":1,
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":608,
                      "y":104},
                    "size":{
                      "width":150,
                      "height":74}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"Open Search Results in Current Window",
                              "target":{
                                "targetType":"page",
                                "url":"search_results.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"27e27eade15a4ca48a80bfaa1a40c728",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":480,
              "y":46},
            "size":{
              "width":330,
              "height":104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48fcc22381142439267e4bcd8b1e4f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":480,
                  "y":46},
                "size":{
                  "width":330,
                  "height":104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}},
{
          "id":"2a1162dd04f24de6b2fcae8e24b3fa0e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Arial-ItalicMT', 'Arial Italic', 'Arial'",
            "fontSize":"18px",
            "fontStyle":"italic",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":299,
              "y":298},
            "size":{
              "width":561,
              "height":67}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"Set text on (Text Field) equal to &quot; &quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetWidgetFormText",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["2a1162dd04f24de6b2fcae8e24b3fa0e"]},
{
                                "exprType":"stringLiteral",
                                "value":" ",
                                "stos":[]}]}]}}]}]}},
          "tabbable":true},
{
          "id":"bf63b16ec0d7428d826701da3f814c5c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF33B353},
            "location":{
              "x":860,
              "y":298},
            "size":{
              "width":147,
              "height":67},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99eeedd01f8f48a182f6ed19aaa88540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial-BoldMT', 'Arial Bold', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF33B353},
                "location":{
                  "x":860,
                  "y":298},
                "size":{
                  "width":147,
                  "height":67},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Search Results in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"search_results.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u9.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dedcfccc1b59419d8105fbb8b7f333f9":{
      "scriptId":"u0"},
    "7650ad05a006498e8d890e609aa66baa":{
      "scriptId":"u1"},
    "7e9fc38d624c4b6484f19b0f55cb8a11":{
      "scriptId":"u2"},
    "f22def401026474aa3e7c21cccf8f7fe":{
      "scriptId":"u3"},
    "24f4f616dac74aff868fc0d4ae3d31d2":{
      "scriptId":"u4"},
    "6950c9515d0b4c6e87a9805765d63432":{
      "scriptId":"u5"},
    "27e27eade15a4ca48a80bfaa1a40c728":{
      "scriptId":"u6"},
    "c48fcc22381142439267e4bcd8b1e4f2":{
      "scriptId":"u7"},
    "2a1162dd04f24de6b2fcae8e24b3fa0e":{
      "scriptId":"u8"},
    "bf63b16ec0d7428d826701da3f814c5c":{
      "scriptId":"u9"},
    "99eeedd01f8f48a182f6ed19aaa88540":{
      "scriptId":"u10"}}});